"""Locate a bundled LabRecorder and bring its Remote Control Server (RCS) up.

Import-safe on any platform (stdlib only) so it is unit-testable on macOS/CI.
A launch only does anything on a machine with a real ``LabRecorder.exe`` (the
frozen Windows bundle, or a dev override dir).

Why this exists: :func:`sensorchrono.orchestration.labrecorder.make_recorder`
already auto-selects the RCS backend when ``localhost:22345`` is reachable. So
if we get a LabRecorder serving RCS *before* ``make_recorder`` runs, the
operator never has to touch LabRecorder — and if we can't, ``make_recorder``
transparently falls back to the manual recorder. This launcher is therefore
pure upside: best-effort automation with a guaranteed manual fallback.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from sensorchrono.orchestration.labrecorder import (
    DEFAULT_RCS_HOST,
    DEFAULT_RCS_PORT,
    RcsRecorder,
)

_LABRECORDER_EXE = "LabRecorder.exe"
_ENV_OVERRIDE = "SENSORCHRONO_LABRECORDER_DIR"


def bundled_labrecorder_dir() -> Path | None:
    """Where a launchable LabRecorder lives, or ``None``.

    * Frozen: PyInstaller unpacks bundled ``datas`` under ``sys._MEIPASS``; the
      spec puts LabRecorder under ``LabRecorder/`` — we require ``LabRecorder.exe``
      to actually be present before claiming it's launchable.
    * Dev / tests: an explicit ``$SENSORCHRONO_LABRECORDER_DIR`` override pointing
      at any existing directory.
    """
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        cand = Path(meipass) / "LabRecorder"
        if (cand / _LABRECORDER_EXE).is_file():
            return cand
    override = os.environ.get(_ENV_OVERRIDE)
    if override and Path(override).is_dir():
        return Path(override)
    return None


def render_config(out_dir: Path | str, *, port: int = DEFAULT_RCS_PORT) -> str:
    """LabRecorder ``Config.cfg`` text: enable the RCS on ``port`` and point
    ``StudyRoot`` at this session's output folder.

    Keys verified against App-LabRecorder's ``LabRecorder.cfg`` (a flat INI —
    no section headers): ``RCSEnabled`` (1/0), ``RCSPort``, ``StudyRoot`` (uses
    forward slashes).
    """
    study_root = Path(out_dir).as_posix()
    return (
        "; Auto-generated by SensorChrono — do not edit.\n"
        f"StudyRoot={study_root}\n"
        "RCSEnabled=1\n"
        f"RCSPort={port}\n"
    )


def wait_for_rcs(
    host: str = DEFAULT_RCS_HOST,
    port: int = DEFAULT_RCS_PORT,
    *,
    deadline_s: float = 15.0,
    poll_interval_s: float = 0.25,
    proc: subprocess.Popen | None = None,
) -> bool:
    """Poll until the RCS port accepts a connection, the deadline passes, or (if
    given) the launched ``proc`` exits early. Unit-testable against a fake
    socket server. Returns whether RCS became reachable."""
    end = time.monotonic() + max(0.0, deadline_s)
    while True:
        if RcsRecorder.is_available(host, port):
            return True
        if proc is not None and proc.poll() is not None:
            return False  # LabRecorder died before serving RCS
        if time.monotonic() >= end:
            return False
        time.sleep(poll_interval_s)


class LabRecorderLauncher:
    """Launch a copy of a bundled LabRecorder configured for headless RCS.

    The bundle may live in a read-only location (Program Files), so we copy it
    to a writable per-session dir and drop a sibling ``Config.cfg`` there before
    launching — that way RCS + StudyRoot are honoured even if a config CLI flag
    isn't. :meth:`stop` only kills a LabRecorder *we* started (never a
    pre-existing operator instance).
    """

    def __init__(
        self,
        source_dir: Path | str,
        *,
        host: str = DEFAULT_RCS_HOST,
        port: int = DEFAULT_RCS_PORT,
    ) -> None:
        self.source_dir = Path(source_dir)
        self.host = host
        self.port = port
        self._proc: subprocess.Popen | None = None
        self._workdir: Path | None = None

    def launch(self, out_dir: Path | str, *, deadline_s: float = 15.0, work_dir: Path | str | None = None) -> bool:
        """Start LabRecorder and wait until RCS is reachable.

        Returns ``True`` if the RCS port is serving by the deadline. Idempotent
        w.r.t. an already-running RCS (returns ``True`` without launching a
        second instance, and records no process to later kill).
        """
        if RcsRecorder.is_available(self.host, self.port):
            return True  # an RCS is already serving — reuse it, don't double-launch
        exe = self.source_dir / _LABRECORDER_EXE
        if not exe.is_file():
            return False
        base = Path(work_dir) if work_dir else Path(tempfile.mkdtemp(prefix="sensorchrono_labrecorder_"))
        dest = base / "LabRecorder"
        shutil.copytree(self.source_dir, dest, dirs_exist_ok=True)
        self._workdir = base
        config = dest / "Config.cfg"
        config.write_text(render_config(out_dir, port=self.port), encoding="utf-8")
        self._proc = subprocess.Popen([str(dest / _LABRECORDER_EXE), str(config)], cwd=str(dest))
        return wait_for_rcs(self.host, self.port, deadline_s=deadline_s, proc=self._proc)

    def stop(self) -> None:
        """Terminate the LabRecorder we launched and clean up its work dir.
        Idempotent; a no-op if we never started a process."""
        proc, self._proc = self._proc, None
        if proc is not None and proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=5.0)
            except subprocess.TimeoutExpired:
                proc.kill()
                try:
                    proc.wait(timeout=5.0)
                except subprocess.TimeoutExpired:  # pragma: no cover - extreme
                    pass
        if self._workdir is not None:
            shutil.rmtree(self._workdir, ignore_errors=True)
            self._workdir = None
